media:
  input: public
  output: /

content:
  - name: about
    label: About
    type: file
    path: src/content/about.md
    format: yaml-frontmatter

    fields:
      - name: texto1
        label: Línea 1
        type: string

      - name: texto2
        label: Línea 2
        type: string

      - name: body
        label: Contenido
        type: rich-text