media:
  input: public
  output: /

content:
  - name: inicio
    label: Inicio
    type: file
    path: src/content/inicio.md
    format: yaml-frontmatter

    fields:
      - name: fondo
        label: Imagen de inicio
        type: file

      - name: linea1
        label: Línea 1
        type: string

      - name: linea2
        label: Línea 2
        type: string

      - name: body
        label: Contenido
        type: rich-text

  - name: nosotros
    label: Nosotros
    type: file
    path: src/content/about.md
    format: yaml-frontmatter

    fields:
      - name: bullet1
        label: Bullet 1
        type: string

      - name: bullet2
        label: Bullet 2
        type: string

      - name: bullet3
        label: Bullet 3
        type: string

      - name: bullet4
        label: Bullet 4
        type: string

      - name: texto1
        label: Texto 1
        type: string

      - name: texto2
        label: Texto 2
        type: string

  - name: proyectos
    label: Proyectos
    type: file
    path: src/content/proyectos.md
    format: yaml-frontmatter

    fields:
      - name: encabezado
        label: Encabezado
        type: string

      - name: titulo1
        label: Título 1
        type: string

      - name: descripcion1
        label: Descripción 1
        type: string

      - name: titulo2
        label: Título 2
        type: string

      - name: descripcion2
        label: Descripción 2
        type: string

      - name: titulo3
        label: Título 3
        type: string

      - name: descripcion3
        label: Descripción 3
        type: string

      - name: titulo4
        label: Título 4
        type: string

      - name: descripcion4
        label: Descripción 4
        type: string